[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "AUTH_GITHUB_ID,AUTH_GITHUB_SECRET,AUTH_SECRET,NEXT_PUBLIC_SANITY_API_VERSION,NEXT_PUBLIC_SANITY_DATASET,NEXT_PUBLIC_SANITY_PROJECT_ID,SANITY_WRITE_TOKEN,SENTRY_AUTH_TOKEN"

[[plugins]]
  package = "@netlify/plugin-nextjs"
